In [2]:
import pandas as pd
import numpy as np
import os

In [3]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\rajan\appdata\local\programs\python\python310\lib\site-packages (3.0.10)

[notice] A new release of pip available: 22.2.2 -> 22.3
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: et-xmlfile in c:\users\rajan\appdata\local\programs\python\python310\lib\site-packages (from openpyxl) (1.1.0)

In [4]:
path = r"D:\SDA_Rajan\CRU_50km_monthly_1901-2020-20221013T040033Z-001\CRU_50km_monthly_1901-2020"

data_dir = os.listdir("../CRU_50km_monthly_1901-2020-20221013T040033Z-001/CRU_50km_monthly_1901-2020")

In [5]:
data_dir[8]

'CRU_50km_pre_1901-2021_monthly_NWH.csv'

In [6]:

def preprocessor(file):
    col_name = ['lon','lat']
    mon = ['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec']
    for i in range(1901,2022):
        for ii in range(12):
            col_name.append(str(i)+"_"+mon[ii])
    read_path = os.path.join(path,file)
    try:
        df = pd.read_csv(read_path)
    except:
        df = pd.read_excel(read_path)

    try:
        df.columns = col_name
    except:
        print("Erro While Renaming Columns")
        print("Len of Col_name", len(col_name),"len of df columns", len(list(df.columns)))
        df.rename(columns = {'Long':'lon','Lat':'lat'}, inplace = True)
        df.columns = col_name[:-2]
        print("Now the len of df columns",len(list(df.columns)))

    return df

In [12]:
df =preprocessor(data_dir[8])
data_dir[8]
df

Erro While Renaming Columns
Len of Col_name 1454 len of df columns 1452
Now the len of df columns 1452

,lon,lat,1901_jan,1901_feb,1901_mar,1901_apr,1901_may,1901_jun,1901_jul,1901_aug,...,2021_jan,2021_feb,2021_mar,2021_apr,2021_may,2021_jun,2021_jul,2021_aug,2021_sep,2021_oct
0,79.75,29.25,120.8,46.4,43.6,2.2,61.1,76.4,395.0,545.0,...,97.1,9.4,15.2,39.3,224.7,354.9,680.8,265.0,390.7,71.4
1,80.25,29.25,114.4,46.4,47.0,3.0,80.1,85.1,414.5,561.8,...,67.9,10.0,16.5,50.9,276.7,511.7,579.1,228.3,283.8,71.1
2,78.25,29.75,121.5,51.9,35.4,2.8,32.2,46.1,417.6,495.4,...,83.1,7.7,11.8,16.9,101.4,201.8,626.3,255.0,333.2,56.2
3,78.75,29.75,155.8,66.7,52.0,3.7,50.4,54.4,432.7,526.1,...,102.3,9.3,21.4,29.9,173.8,280.9,646.6,245.5,334.3,60.0
4,79.25,29.75,167.6,68.3,63.6,4.2,65.1,61.8,413.1,501.7,...,98.2,10.1,29.2,41.4,226.3,362.7,578.8,209.5,303.2,63.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,75.75,36.25,8.2,6.0,5.9,18.6,27.2,27.8,22.6,6.7,...,26.1,17.6,44.9,43.0,37.8,19.1,22.4,16.7,8.7,8.9
124,76.25,36.25,5.5,4.5,4.7,15.8,22.0,22.5,20.4,6.1,...,16.9,18.7,45.1,32.3,32.1,19.0,22.7,14.8,7.7,6.1
125,74.25,36.75,16.9,8.5,13.2,23.5,50.1,48.0,17.8,6.1,...,32.6,18.2,46.9,56.2,44.5,15.0,14.5,15.8,7.1,14.8
126,74.75,36.75,9.2,5.9,9.0,17.5,32.5,30.6,14.7,5.5,...,21.3,15.2,33.4,41.7,37.8,14.8,13.1,15.6,7.2,9.8
127,75.25,36.75,8.2,5.8,7.7,17.6,30.1,32.3,18.2,6.3,...,22.2,16.7,34.0,45.2,42.7,19.6,16.7,18.5,7.6,9.6

In [11]:
df = pd.read_csv(os.path.join(path,"CRU_50km_pre_1901-2021_monthly_NWH.csv"))
df

,79.25,29.25,124,39.3,35.5,1.5,38.8,61.4,413.8,544.4,...,96.2,7.4.3,10.4.4,21.2.1,141.2,280.4,682.5,275.7,372.3.1,77.5.1
0,79.75,29.25,120.8,46.4,43.6,2.2,61.1,76.4,395.0,545.0,...,97.1,9.4,15.2,39.3,224.7,354.9,680.8,265.0,390.7,71.4
1,80.25,29.25,114.4,46.4,47.0,3.0,80.1,85.1,414.5,561.8,...,67.9,10.0,16.5,50.9,276.7,511.7,579.1,228.3,283.8,71.1
2,78.25,29.75,121.5,51.9,35.4,2.8,32.2,46.1,417.6,495.4,...,83.1,7.7,11.8,16.9,101.4,201.8,626.3,255.0,333.2,56.2
3,78.75,29.75,155.8,66.7,52.0,3.7,50.4,54.4,432.7,526.1,...,102.3,9.3,21.4,29.9,173.8,280.9,646.6,245.5,334.3,60.0
4,79.25,29.75,167.6,68.3,63.6,4.2,65.1,61.8,413.1,501.7,...,98.2,10.1,29.2,41.4,226.3,362.7,578.8,209.5,303.2,63.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,75.75,36.25,8.2,6.0,5.9,18.6,27.2,27.8,22.6,6.7,...,26.1,17.6,44.9,43.0,37.8,19.1,22.4,16.7,8.7,8.9
124,76.25,36.25,5.5,4.5,4.7,15.8,22.0,22.5,20.4,6.1,...,16.9,18.7,45.1,32.3,32.1,19.0,22.7,14.8,7.7,6.1
125,74.25,36.75,16.9,8.5,13.2,23.5,50.1,48.0,17.8,6.1,...,32.6,18.2,46.9,56.2,44.5,15.0,14.5,15.8,7.1,14.8
126,74.75,36.75,9.2,5.9,9.0,17.5,32.5,30.6,14.7,5.5,...,21.3,15.2,33.4,41.7,37.8,14.8,13.1,15.6,7.2,9.8
127,75.25,36.75,8.2,5.8,7.7,17.6,30.1,32.3,18.2,6.3,...,22.2,16.7,34.0,45.2,42.7,19.6,16.7,18.5,7.6,9.6

In [9]:
df['lat']

KeyError: 'lat'

In [10]:
read_path = os.path.join(path,data_dir[20])
try:
    df = pd.read_csv(read_path)
except:
    df = pd.read_excel(read_path)

ValueError: Excel file format cannot be determined, you must specify an engine manually.

In [ ]:
df

In [ ]:
#Years=int((df.shape[1]-2)/12)

In [ ]:
try:
    df.columns = col_name
except:
    print("Already have columns Name")
    df.rename(columns = {'Long':'lon','Lat':'lat'}, inplace = True)
df

In [19]:
bird_df = df.query('-68.7 < lon < 98.25')
bird_df = bird_df.query('8.4 < lat < 37.6')
bird_df

,lon,lat,1901_jan,1901_feb,1901_mar,1901_apr,1901_may,1901_jun,1901_jul,1901_aug,...,2021_jan,2021_feb,2021_mar,2021_apr,2021_may,2021_jun,2021_jul,2021_aug,2021_sep,2021_oct
0,79.75,29.25,120.8,46.4,43.6,2.2,61.1,76.4,395.0,545.0,...,97.1,9.4,15.2,39.3,224.7,354.9,680.8,265.0,390.7,71.4
1,80.25,29.25,114.4,46.4,47.0,3.0,80.1,85.1,414.5,561.8,...,67.9,10.0,16.5,50.9,276.7,511.7,579.1,228.3,283.8,71.1
2,78.25,29.75,121.5,51.9,35.4,2.8,32.2,46.1,417.6,495.4,...,83.1,7.7,11.8,16.9,101.4,201.8,626.3,255.0,333.2,56.2
3,78.75,29.75,155.8,66.7,52.0,3.7,50.4,54.4,432.7,526.1,...,102.3,9.3,21.4,29.9,173.8,280.9,646.6,245.5,334.3,60.0
4,79.25,29.75,167.6,68.3,63.6,4.2,65.1,61.8,413.1,501.7,...,98.2,10.1,29.2,41.4,226.3,362.7,578.8,209.5,303.2,63.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,75.75,36.25,8.2,6.0,5.9,18.6,27.2,27.8,22.6,6.7,...,26.1,17.6,44.9,43.0,37.8,19.1,22.4,16.7,8.7,8.9
124,76.25,36.25,5.5,4.5,4.7,15.8,22.0,22.5,20.4,6.1,...,16.9,18.7,45.1,32.3,32.1,19.0,22.7,14.8,7.7,6.1
125,74.25,36.75,16.9,8.5,13.2,23.5,50.1,48.0,17.8,6.1,...,32.6,18.2,46.9,56.2,44.5,15.0,14.5,15.8,7.1,14.8
126,74.75,36.75,9.2,5.9,9.0,17.5,32.5,30.6,14.7,5.5,...,21.3,15.2,33.4,41.7,37.8,14.8,13.1,15.6,7.2,9.8
127,75.25,36.75,8.2,5.8,7.7,17.6,30.1,32.3,18.2,6.3,...,22.2,16.7,34.0,45.2,42.7,19.6,16.7,18.5,7.6,9.6